# Generated by Django 4.2 on 2024-01-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_quatity_orderdetails_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetails',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
