# Generated by Django 4.2 on 2024-01-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_quatity_cartdetails_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
