# Generated by Django 4.2 on 2024-01-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cartdetails_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetails',
            name='price',
        ),
    ]
