# Generated by Django 4.2 on 2023-12-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_review_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'ProductImage', 'verbose_name_plural': 'ProductImages'},
        ),
    ]
